#:schema node_modules/wrangler/config-schema.json
name = "qtron-sublink"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "163a1fc8971941bfafe093695c999fdf" }
]

[assets]
directory = "./public"
